/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guidemo;

import com.mybank.domain.*;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
/**
 *
 * @author pass
 */
public class GUIDemo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIDemo.class.getName());

    /**
     * Creates new form GUIDemo
     */
    public GUIDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        showbtn = new javax.swing.JButton();
        reportbtn = new javax.swing.JButton();
        aboutbtn = new javax.swing.JButton();
        clients = new javax.swing.JComboBox<>();
        Uppercase = new javax.swing.JTextField();
        instruction = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientsinfo = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showbtn.setText("Show");
        showbtn.addActionListener(this::showbtnActionPerformed);

        reportbtn.setText("Report");
        reportbtn.addActionListener(this::reportbtnActionPerformed);

        aboutbtn.setText("About");
        aboutbtn.addActionListener(this::aboutbtnActionPerformed);

        clients.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Uppercase.setText("MyBank Clients                                                                                              X _");
        Uppercase.addActionListener(this::UppercaseActionPerformed);

        instruction.setText("Choose a client name and press \"Show\" button");
        instruction.addActionListener(this::instructionActionPerformed);

        clientsinfo.setColumns(20);
        clientsinfo.setRows(5);
        clientsinfo.setText("John Doe, customer #1\n------------------------\nAccounts:\n#0 - Cheking: $1500, owerdraft: $200\n#1 - Savings: $1000, interest rate: 5%");
        jScrollPane1.setViewportView(clientsinfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clients, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addComponent(Uppercase, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(instruction)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Uppercase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reportbtn)
                        .addGap(18, 18, 18)
                        .addComponent(aboutbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clients, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(instruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void loadData() {

        try (BufferedReader br = new BufferedReader(new FileReader("test.dat"))) {

            String line;
            Customer current = null;

            while ((line = br.readLine()) != null) {

                line = line.trim();
                if (line.isEmpty()) continue;

                String[] p = line.split("\t");

                if (p.length == 3 && !p[0].equals("S") && !p[0].equals("C")) {

                    Bank.addCustomer(p[0], p[1]);

                    current = Bank.getCustomer(Bank.getNumberOfCustomers() - 1);

                } else if (p[0].equals("S")) {

                    current.addAccount(new SavingsAccount(
                            Double.parseDouble(p[1]),
                            Double.parseDouble(p[2])
                    ));

                } else if (p[0].equals("C")) {

                    current.addAccount(new CheckingAccount(
                            Double.parseDouble(p[1])
                    ));
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        
    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
    Customer c = Bank.getCustomer(clients.getSelectedIndex());

        StringBuilder sb = new StringBuilder();

        sb.append(c.getLastName()).append(", ").append(c.getFirstName()).append("\n\n");

        for (int i = 0; i < c.getNumberOfAccounts(); i++) {

            Account a = c.getAccount(i);

            String type = (a instanceof SavingsAccount)
                    ? "Savings"
                    : "Checking";

            sb.append("#").append(i)
              .append(" - ").append(type)
              .append(": $").append(a.getBalance())
              .append("\n");
        }

        clientsinfo.setText(sb.toString());
    }//GEN-LAST:event_showbtnActionPerformed

    private void UppercaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UppercaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UppercaseActionPerformed

    private void instructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructionActionPerformed

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
       
        StringBuilder sb = new StringBuilder();

        sb.append("CUSTOMERS REPORT\n================\n\n");

        for (int i = 0; i < Bank.getNumberOfCustomers(); i++) {

            Customer c = Bank.getCustomer(i);

            sb.append(c.getLastName())
              .append(", ")
              .append(c.getFirstName())
              .append("\n");

            for (int j = 0; j < c.getNumberOfAccounts(); j++) {

                Account a = c.getAccount(j);

                String type = (a instanceof SavingsAccount)
                        ? "Savings"
                        : "Checking";

                sb.append("  ")
                  .append(type)
                  .append(": $")
                  .append(a.getBalance())
                  .append("\n");
            }

            sb.append("\n");
        }

        clientsinfo.setText(sb.toString());
    
    }//GEN-LAST:event_reportbtnActionPerformed

    private void aboutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutbtnActionPerformed
        
        JOptionPane.showMessageDialog(this,
                "MyBank GUI Demo\nAuthor: Hirich Yevhenii, 34 group",
                "About",
                JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_aboutbtnActionPerformed
    
    private void initClients() {

        clients.removeAllItems();

        for (int i = 0; i < Bank.getNumberOfCustomers(); i++) {

            Customer c = Bank.getCustomer(i);

            clients.addItem(c.getLastName() + ", " + c.getFirstName());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {

            GUIDemo gui = new GUIDemo();

            gui.loadData();
            gui.initClients();

            gui.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Uppercase;
    private javax.swing.JButton aboutbtn;
    private javax.swing.JComboBox<String> clients;
    private javax.swing.JTextArea clientsinfo;
    private javax.swing.JTextField instruction;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reportbtn;
    private javax.swing.JButton showbtn;
    // End of variables declaration//GEN-END:variables
}
